# *******************************************************
# infra/dev/mosquitto.conf
# Configuration du broker MQTT — environnement Dev UNIQUEMENT.
# *******************************************************

# 1883 = port MQTT standard, sans chiffrement.
listener 1883

# En Dev, on autorise les connexions sans authentification pour simplifier le développement local.
allow_anonymous true

# Logs en sortie standard du conteneur
# MQTT en direct pendant qu'on développe l'agent Edge.
log_dest stdout
log_type all
