spring.application.name=EdgeSentinel-Backend

# Configuration MQTT — cohérente avec edge/config/config.yaml
mqtt.broker.url=tcp://localhost:1883
mqtt.broker.clientId=edgesentinel-backend
mqtt.topic=edge/+/events
